# This is the config version number. This will auto-increment each time a config update is done. DO NOT TOUCH THIS!!!!!
file-version: 2

######################################################################
#                    F O R M A T T I N G   N O T E S                 #
######################################################################

# This plugin uses MiniMessage to format text. This means that color codes such as &c and decorations such as &l will not work.
# To use MiniMessage, see this link: https://docs.advntr.dev/minimessage/format.html
# Strict mode is not enabled in this plugin, so don't feel like you need to close your tags :)
# You may also use <reset> if you like

######################################################################
#                     P L U G I N   S E T T I N G S                  #
######################################################################

# A list of dimensions. You may set these to be disabled or not, and also set them to be bypassable
# If a dimension is not bypassable, only OPs may enter it, players with the bypass permission may not.
# NOTE: The above also includes players with "*" permissions, such as server owners! You MUST be OP to bypass a non-bypassable world!
dimensions:
  end:
    paused: false
    bypassable: true
    alert:
      # Allows you to alert players if they attempt to teleport to disabled worlds
      title:
        # Set if a title will be displayed if a player attempts to enter a disabled world
        enabled: true
        title: "Sorry, <light_purple>The End</light_purple> is currently <red>paused</red>!"
        subtitle: "As a result, you may not enter <light_purple>The End</light_purple> or <light_purple>activate End Portals</light_purple>"
      chat:
        # Set if a chat message will be sent to the player if they attempt to enter a disabled world
        enabled: false
        message: "YOU SHALL NOT PASS"
      on-toggle:
        # Alert players when the dimension is toggled. This will always be a chat message. Use %state% to display the current state of the dimension.
        enabled: true
        message: "Attention! <light_purple>The End</light_purple> has been %state%!"
  nether:
    paused: false
    bypassable: true
    # Applies a bit of knockback velocity when a player tries to teleport
    bounce-back: true
    alert:
      # Allows you to alert players if they attempt to teleport to disabled worlds
      title:
        # Set if a title will be displayed if a player attempts to enter a disabled world
        enabled: true
        title: "Sorry, <red>The Nether</red> is currently <red>paused</red>!"
        subtitle: "As a result, you may not enter <red>The Nether</red> or <red>activate Nether Portals</red>"
      chat:
        # Set if a chat message will be sent to the player if they attempt to enter a disabled world
        enabled: false
        message: "YOU SHALL NOT PASS"
      on-toggle:
        # Alert players when the dimension is toggled. This will always be a chat message. Use %state% to display the current state of the dimension.
        enabled: true
        message: "Attention! <red>The Nether</red> has been %state%!"


# The name of the world you want to kick players to if they are currently in a dimension when it's paused.
# If a player attempts to teleport to a paused dimension, they'll be teleported back to their previous world's spawn point. This value is ignored in that scenario
kick-world: "world"

# If we should try to teleport them to their bed first
try-bed-first: true

######################################################################
#                      C H A T   S E T T I N G S                     #
######################################################################
bypass-language-check: false
# Select your language. Current supported languages are: [en_US]
# Want to create your own translation? Visit here: https://github.com/TerrorByteTW/Honeypot/wiki/Translating-Honeypot
language: en_US

######################################################################
#                           C R E D I T S                            #
######################################################################
# Credit where credit is due! If you contribute to Honeypot in any way, you'll get your name here
# Code Contributions: TerrorByteTW
# The next line is ignored, just a dummy value so the credits above get populated within the config!
thank-you: true
